### ISSUE TITLE
Performance api throws error when trigger a same action in an action effect

### ISSUE THREAD

**Issue by hreflee** [bhovhannes/redux-profiler#651]
The following calling path will trigger a `Failed to execute 'measure' on 'Performance': The mark 'xxx:0:start' does not exist` error in redux-profiler. I create a example to show this bug in https://codesandbox.io/s/quiet-leaf-35b88 :

1. Click "bugAdd" and trigger a thunk action `asyncAdd`
2. `asyncAdd` trigger action `syncAdd`
3. The change in store made by `syncAdd` trigger a effect in `Helper.jsx`
4. Effect in `Helper.jsx` trigger `syncAdd`
5. Error shows

**Comment by bhovhannes** [comment]
@hreflee thank you for catching and fixing this!

**Comment by bhovhannes** [comment]
Fix is released in version `1.0.8`

**Comment by hreflee** [comment]
Hi @bhovhannes ! I try to upgrade my local redux-profiler dependence to 1.0.9 but it seems the `dist` folder I got from npm is still the version of `1.0.7`. Could you please help check?

**Comment by bhovhannes** [comment]
Hi, maybe I forgot to build the package before publish. Please try version `1.0.10`.

**Comment by hreflee** [comment]
Thank you!
