### ISSUE TITLE
How to see the results of the profiler?

### ISSUE THREAD

**Issue by Amatewasu** [bhovhannes/redux-profiler#653]
Thank you for your redux profiler that looks really interesting.

I do not understand how to look at the results though.
Is it the React Dev Tool or in another location?

Thank you a lot!

**Comment by bhovhannes** [comment]
Hi 👋 

After going through integration steps written in readme, you can profile your app using Chrome DevTools Profiler - https://developer.chrome.com/docs/devtools/evaluate-performance/#record

`redux-profiler` will add blocks there, showing how long each redux action takes.

**Comment by Amatewasu** [comment]
Thank you for your super-quick answer. It was probably misconfigured before.

I add a screenshot of the result in case other people have the same question:
![image](https://user-images.githubusercontent.com/747613/143561471-b176c451-d416-41b4-8b0c-705e386e8aec.png)
There's a block named _timings_ that has been added and I hover a block with my mouse to look at the duration of the action.
